/**
 * Human-readable catalog of the ind-ds web components.
 *
 * Source of truth for tags, props and state unions is `@ind-ds/core/dist/docs.json`
 * (generated by Stencil). This file adds a browsing taxonomy and factual, one-line
 * descriptions grounded in each component's real props — nothing here invents
 * capabilities that don't exist in the package.
 *
 * The catalog is verified against docs.json at build time by
 * `scripts/validate-content.mjs`, which fails the build if a tag here is missing
 * from the built package (or vice-versa). That keeps the count and list honest.
 */

export interface ComponentCategory {
  id: string;
  label: string;
  blurb: string;
}

export interface ComponentEntry {
  /** Custom element tag, e.g. "ind-led". */
  tag: string;
  /** Browsing category id. */
  category: string;
  /** Atomic-design tier as built. */
  tier: 'atom' | 'molecule' | 'organism';
  /** Factual one-line description derived from the component's real props. */
  description: string;
}

export const CATEGORIES: ComponentCategory[] = [
  { id: 'equipment', label: 'Process equipment', blurb: 'Pumps, valves, motors, tanks and other P&ID symbols with semantic equipment states.' },
  { id: 'indicators', label: 'Indicators', blurb: 'LEDs, status dots and badges that show operational state at a glance.' },
  { id: 'alarms', label: 'Alarms', blurb: 'ISA-18.2-aware alarm display with priority, acknowledgement and summaries.' },
  { id: 'values', label: 'Values & measurement', blurb: 'Process values, gauges, setpoints and units with tabular numerals.' },
  { id: 'dataviz', label: 'Data visualization', blurb: 'Sparklines, trends, KPIs and historical views for monitoring.' },
  { id: 'controls', label: 'Controls', blurb: 'Buttons, knobs, mode selectors, start/stop and emergency-stop controls.' },
  { id: 'inputs', label: 'Inputs', blurb: 'Form inputs, toggles and pickers tuned for dense operator screens.' },
  { id: 'navigation', label: 'Navigation', blurb: 'Tabs, breadcrumbs, trees and sidebar navigation for multi-view apps.' },
  { id: 'cards', label: 'Cards & faceplates', blurb: 'Equipment faceplates and status cards that combine state, values and context.' },
  { id: 'connectivity', label: 'Status & connectivity', blurb: 'Connection indicators, status bars and live-data binding elements.' },
  { id: 'layout', label: 'Layout & foundation', blurb: 'Icons, labels, dividers, dialogs and canvas primitives for composition.' },
  { id: 'shell', label: 'Application shell & dashboards', blurb: 'Headers, dashboards and full control panels for complete HMI/SCADA screens.' },
];

export const COMPONENTS: ComponentEntry[] = [
  // ── Process equipment ───────────────────────────────────────────────────
  { tag: 'ind-pump', category: 'equipment', tier: 'atom', description: 'Pump symbol with the five equipment states (running/stopped/fault/warning/maintenance) and a tag identifier.' },
  { tag: 'ind-valve', category: 'equipment', tier: 'atom', description: 'Valve symbol with open/closed/transit/fault positions and horizontal or vertical orientation.' },
  { tag: 'ind-motor', category: 'equipment', tier: 'atom', description: 'Motor symbol carrying the standard equipment state set and an asset tag.' },
  { tag: 'ind-fan', category: 'equipment', tier: 'atom', description: 'Fan symbol with equipment states; animates only while running (respects reduced motion).' },
  { tag: 'ind-compressor', category: 'equipment', tier: 'atom', description: 'Compressor symbol with the standard equipment state set and a tag.' },
  { tag: 'ind-conveyor', category: 'equipment', tier: 'atom', description: 'Conveyor symbol with run direction and equipment states.' },
  { tag: 'ind-heater', category: 'equipment', tier: 'atom', description: 'Heater symbol with equipment states for thermal process schematics.' },
  { tag: 'ind-cooler', category: 'equipment', tier: 'atom', description: 'Cooler symbol with equipment states for thermal process schematics.' },
  { tag: 'ind-tank', category: 'equipment', tier: 'atom', description: 'Tank with a fill level, optional value readout and low/high alarm marking.' },
  { tag: 'ind-silo', category: 'equipment', tier: 'atom', description: 'Silo with fill level and alarm marking for bulk-material storage.' },
  { tag: 'ind-pipe', category: 'equipment', tier: 'atom', description: 'Pipe segment with orientation, thickness and an active-flow indication.' },
  { tag: 'ind-process-symbol', category: 'equipment', tier: 'atom', description: 'Generic process symbol with selectable shape and normal/warning/fault states.' },
  { tag: 'ind-scara-canvas', category: 'equipment', tier: 'atom', description: 'SCARA robot arm canvas driven by joint angles and link lengths, with idle/moving/fault states.' },

  // ── Indicators ──────────────────────────────────────────────────────────
  { tag: 'ind-led', category: 'indicators', tier: 'atom', description: 'Status LED with the five equipment states, optional blink and a label.' },
  { tag: 'ind-status-dot', category: 'indicators', tier: 'atom', description: 'Small status dot covering equipment and generic semantic states, with optional blink.' },
  { tag: 'ind-badge', category: 'indicators', tier: 'atom', description: 'Text badge with process-state and semantic variants, solid or outline.' },
  { tag: 'ind-signal-quality', category: 'indicators', tier: 'atom', description: 'Signal-strength bars for wireless or link quality.' },
  { tag: 'ind-heartbeat', category: 'indicators', tier: 'atom', description: 'Liveness pulse driven by an alive flag and expected interval.' },
  { tag: 'ind-counter', category: 'indicators', tier: 'atom', description: 'Compact numeric counter chip with semantic variants and a zero-dot mode.' },

  // ── Alarms ────────────────────────────────────────────────────────────────
  { tag: 'ind-alarm', category: 'alarms', tier: 'atom', description: 'Single alarm indicator with ISA-18.2 priority (HH/H/L/LL), acknowledged state and timestamp.' },
  { tag: 'ind-alarm-count', category: 'alarms', tier: 'atom', description: 'Chip showing per-priority alarm counts (HH/H/L/LL) with an optional total.' },
  { tag: 'ind-alarm-badge-group', category: 'alarms', tier: 'molecule', description: 'Grouped alarm-count badges across all four priorities.' },
  { tag: 'ind-alarm-row', category: 'alarms', tier: 'molecule', description: 'Alarm list row with priority, tag, message, time and an acknowledge action.' },
  { tag: 'ind-alarm-summary', category: 'alarms', tier: 'organism', description: 'Header summary of active and unacknowledged alarm counts by priority.' },
  { tag: 'ind-alarm-panel', category: 'alarms', tier: 'organism', description: 'Full alarm list, sorted unacknowledged-first by ISA-18.2 priority, with ack and ack-all.' },

  // ── Values & measurement ──────────────────────────────────────────────────
  { tag: 'ind-value', category: 'values', tier: 'atom', description: 'Process value with unit, precision, trend arrow and alarm marking; tabular numerals.' },
  { tag: 'ind-unit-label', category: 'values', tier: 'atom', description: 'Engineering-unit label for pairing with a value.' },
  { tag: 'ind-timestamp', category: 'values', tier: 'atom', description: 'Formatted timestamp with locale and seconds control.' },
  { tag: 'ind-gauge', category: 'values', tier: 'atom', description: 'Radial gauge with min/max, colored zones, unit and precision.' },
  { tag: 'ind-linear-gauge', category: 'values', tier: 'atom', description: 'Linear gauge with zones and an optional setpoint marker, horizontal or vertical.' },
  { tag: 'ind-setpoint', category: 'values', tier: 'atom', description: 'Setpoint field showing the target next to the current process value (PV).' },
  { tag: 'ind-progress', category: 'values', tier: 'atom', description: 'Linear progress bar with semantic variants and an indeterminate mode.' },
  { tag: 'ind-progress-ring', category: 'values', tier: 'atom', description: 'Circular progress ring with semantic variants and an indeterminate mode.' },

  // ── Data visualization ────────────────────────────────────────────────────
  { tag: 'ind-sparkline', category: 'dataviz', tier: 'atom', description: 'Inline sparkline from a number series with variants and optional area/marker.' },
  { tag: 'ind-xy-point', category: 'dataviz', tier: 'atom', description: 'Single XY plot point with bounds and an optional motion trail.' },
  { tag: 'ind-trend-widget', category: 'dataviz', tier: 'molecule', description: 'Compact trend card pairing a live value with a sparkline series.' },
  { tag: 'ind-kpi-card', category: 'dataviz', tier: 'molecule', description: 'KPI card with value, unit, delta and good/bad/neutral trend styling.' },
  { tag: 'ind-energy-card', category: 'dataviz', tier: 'molecule', description: 'Energy card combining an instantaneous value, total and trend series.' },
  { tag: 'ind-trend-viewer', category: 'dataviz', tier: 'organism', description: 'Multi-series trend viewer for comparing tags over time.' },
  { tag: 'ind-historian-viewer', category: 'dataviz', tier: 'organism', description: 'Historical sample viewer for a single tag with unit and precision.' },

  // ── Controls ──────────────────────────────────────────────────────────────
  { tag: 'ind-button', category: 'controls', tier: 'atom', description: 'Industrial button with default/primary/danger/ghost variants and optional hold-to-confirm.' },
  { tag: 'ind-estop', category: 'controls', tier: 'atom', description: 'Emergency-stop control with engaged state, activate and reset events.' },
  { tag: 'ind-knob', category: 'controls', tier: 'atom', description: 'Rotary knob input with min/max/step, unit and value display.' },
  { tag: 'ind-slider', category: 'controls', tier: 'atom', description: 'Slider input with min/max/step, unit and value display.' },
  { tag: 'ind-selector-switch', category: 'controls', tier: 'atom', description: 'Multi-position selector switch (e.g. Off/Manual/Auto).' },
  { tag: 'ind-mode-selector', category: 'controls', tier: 'molecule', description: 'Operating-mode selector with configurable positions and a change event.' },
  { tag: 'ind-setpoint-control', category: 'controls', tier: 'molecule', description: 'Editable setpoint with the current PV, bounds and step, emitting on change.' },
  { tag: 'ind-speed-control', category: 'controls', tier: 'molecule', description: 'Speed input rendered as a knob or slider with engineering units.' },
  { tag: 'ind-start-stop-control', category: 'controls', tier: 'molecule', description: 'Start/stop control with running/starting/stopping/stopped/fault states and hold-to-start.' },
  { tag: 'ind-temperature-control', category: 'controls', tier: 'molecule', description: 'Temperature setpoint control with PV, mode and bounds.' },
  { tag: 'ind-command-group', category: 'controls', tier: 'molecule', description: 'Grouped command buttons, attached or spaced, horizontal or vertical.' },
  { tag: 'ind-toolbar-action', category: 'controls', tier: 'molecule', description: 'Toolbar action button with an optional counter badge.' },
  { tag: 'ind-recipe-selector', category: 'controls', tier: 'molecule', description: 'Recipe picker with a load action for batch operations.' },

  // ── Inputs ────────────────────────────────────────────────────────────────
  { tag: 'ind-input', category: 'inputs', tier: 'atom', description: 'Text/number input with label, validation state and input/change events.' },
  { tag: 'ind-textarea', category: 'inputs', tier: 'atom', description: 'Multi-line text input with default or monospace variant and auto-scroll.' },
  { tag: 'ind-checkbox', category: 'inputs', tier: 'atom', description: 'Checkbox with indeterminate state and a change event.' },
  { tag: 'ind-toggle', category: 'inputs', tier: 'atom', description: 'On/off toggle with optional on/off text labels.' },
  { tag: 'ind-select', category: 'inputs', tier: 'atom', description: 'Select dropdown driven by an options list with validation state.' },
  { tag: 'ind-datetime-picker', category: 'inputs', tier: 'atom', description: 'Date/time picker with min/max/step and validation state.' },
  { tag: 'ind-batch-parameter-row', category: 'inputs', tier: 'molecule', description: 'Editable batch-parameter row with target, bounds, unit and validation.' },

  // ── Navigation ────────────────────────────────────────────────────────────
  { tag: 'ind-breadcrumb-item', category: 'navigation', tier: 'atom', description: 'Breadcrumb segment with current/last state and a navigate event.' },
  { tag: 'ind-tab', category: 'navigation', tier: 'atom', description: 'Tab control with selected/disabled state and a select event.' },
  { tag: 'ind-tree-node', category: 'navigation', tier: 'atom', description: 'Tree node with level, expand/collapse and selection.' },
  { tag: 'ind-nav-item', category: 'navigation', tier: 'molecule', description: 'Navigation item with active state, badge and select event.' },
  { tag: 'ind-sidebar-group', category: 'navigation', tier: 'molecule', description: 'Collapsible sidebar group with a badge and toggle event.' },
  { tag: 'ind-sidebar-nav', category: 'navigation', tier: 'organism', description: 'Sidebar navigation container composed from groups and items.' },

  // ── Cards & faceplates ────────────────────────────────────────────────────
  { tag: 'ind-pump-card', category: 'cards', tier: 'molecule', description: 'Pump faceplate with state plus flow and pressure readouts.' },
  { tag: 'ind-motor-card', category: 'cards', tier: 'molecule', description: 'Motor faceplate with state plus speed, load and current.' },
  { tag: 'ind-valve-card', category: 'cards', tier: 'molecule', description: 'Valve faceplate with position and open/closed/transit/fault state.' },
  { tag: 'ind-tank-level-card', category: 'cards', tier: 'molecule', description: 'Tank faceplate with level, capacity, unit and low/high alarm.' },
  { tag: 'ind-equipment-status-card', category: 'cards', tier: 'molecule', description: 'Equipment status card with state, custom label and detail line.' },
  { tag: 'ind-health-card', category: 'cards', tier: 'molecule', description: 'Health summary card with state and detail for an asset.' },
  { tag: 'ind-device-info-card', category: 'cards', tier: 'molecule', description: 'Device card with model, vendor, serial, firmware and connection state.' },
  { tag: 'ind-device-connection-card', category: 'cards', tier: 'molecule', description: 'Device connection card with endpoint, protocol, latency and connection state.' },
  { tag: 'ind-network-status-card', category: 'cards', tier: 'molecule', description: 'Network card with address, level, RX/TX throughput and connection state.' },
  { tag: 'ind-tag-card', category: 'cards', tier: 'molecule', description: 'Tag card combining value, unit, trend, alarm and equipment state.' },
  { tag: 'ind-fill-row', category: 'cards', tier: 'molecule', description: 'Labeled fill/progress row with value, unit and severity styling.' },
  { tag: 'ind-historical-value-row', category: 'cards', tier: 'molecule', description: 'Historical reading row with value, unit, quality and time.' },
  { tag: 'ind-audit-row', category: 'cards', tier: 'molecule', description: 'Audit-trail row with user, action, detail and time.' },
  { tag: 'ind-event-row', category: 'cards', tier: 'molecule', description: 'Event-log row with source, severity, message and time.' },

  // ── Status & connectivity ─────────────────────────────────────────────────
  { tag: 'ind-connection-indicator', category: 'connectivity', tier: 'atom', description: 'Connection indicator with connected/connecting/disconnected/error states.' },
  { tag: 'ind-status-bar', category: 'connectivity', tier: 'organism', description: 'Application status bar with a semantic state, message and slot for extras.' },
  { tag: 'ind-mqtt-tag-binding', category: 'connectivity', tier: 'molecule', description: 'Display element for an MQTT topic showing value, unit, QoS and connection state.' },
  { tag: 'ind-opcua-tag-binding', category: 'connectivity', tier: 'molecule', description: 'Display element for an OPC UA node showing value, unit, quality and connection state.' },
  { tag: 'ind-mqtt-monitor', category: 'connectivity', tier: 'organism', description: 'Live MQTT message monitor with filtering, pause and clear.' },

  // ── Layout & foundation ───────────────────────────────────────────────────
  { tag: 'ind-icon', category: 'layout', tier: 'atom', description: 'Icon primitive with a name, size and accessible label.' },
  { tag: 'ind-label', category: 'layout', tier: 'atom', description: 'Form/field label with tone, size, required marker and uppercase option.' },
  { tag: 'ind-tag-name', category: 'layout', tier: 'atom', description: 'Asset-tag identifier (e.g. P-101) with an optional boxed style.' },
  { tag: 'ind-divider', category: 'layout', tier: 'atom', description: 'Horizontal or vertical divider.' },
  { tag: 'ind-dialog', category: 'layout', tier: 'atom', description: 'Modal dialog with heading, sizes and backdrop-close control.' },
  { tag: 'ind-canvas-layer', category: 'layout', tier: 'atom', description: 'Absolute-positioning layer (x/y/z, rotation, scale) for composing schematic canvases.' },
  { tag: 'ind-shelf-canvas', category: 'layout', tier: 'atom', description: 'Grid shelf canvas with rows, columns and slots for warehouse/storage views.' },
  { tag: 'ind-context-toolbar', category: 'layout', tier: 'organism', description: 'Contextual toolbar with heading and subtitle for a screen or panel.' },
  { tag: 'ind-command-center', category: 'layout', tier: 'organism', description: 'Command-center grid container for arranging control widgets in columns.' },

  // ── Application shell & dashboards ─────────────────────────────────────────
  { tag: 'ind-app-header', category: 'shell', tier: 'organism', description: 'Application header with brand, machine id, connection state and version.' },
  { tag: 'ind-asset-overview', category: 'shell', tier: 'organism', description: 'Overview grid of assets with headings for a fleet or area.' },
  { tag: 'ind-machine-overview', category: 'shell', tier: 'organism', description: 'Machine overview with id, OEE, state and a grid of sub-widgets.' },
  { tag: 'ind-equipment-dashboard', category: 'shell', tier: 'organism', description: 'Dashboard grid for arranging equipment cards in columns.' },
  { tag: 'ind-energy-dashboard', category: 'shell', tier: 'organism', description: 'Energy dashboard aggregating energy cards with a headline total.' },
  { tag: 'ind-oee-dashboard', category: 'shell', tier: 'organism', description: 'OEE dashboard breaking out availability, performance and quality.' },
  { tag: 'ind-production-dashboard', category: 'shell', tier: 'organism', description: 'Production dashboard container with heading and subtitle.' },
  { tag: 'ind-production-line-overview', category: 'shell', tier: 'organism', description: 'Production-line overview composed from a list of stations.' },
  { tag: 'ind-production-cell', category: 'shell', tier: 'organism', description: 'Production-cell grid with a cell id and rolled-up state.' },
  { tag: 'ind-maintenance-dashboard', category: 'shell', tier: 'organism', description: 'Maintenance dashboard with MTBF, MTTR, open and overdue work orders.' },
  { tag: 'ind-batch-control-panel', category: 'shell', tier: 'organism', description: 'Batch control panel with phase, progress, parameters and start/stop/hold.' },
  { tag: 'ind-motor-control-panel', category: 'shell', tier: 'organism', description: 'Motor control panel with speed, load, current, mode and start/stop.' },
  { tag: 'ind-pump-control-panel', category: 'shell', tier: 'organism', description: 'Pump control panel with flow, pressure, mode and start/stop.' },
  { tag: 'ind-valve-control-panel', category: 'shell', tier: 'organism', description: 'Valve control panel with position, modulation and open/close/stop.' },
  { tag: 'ind-process-control-panel', category: 'shell', tier: 'organism', description: 'Process control panel pairing PV and setpoint with mode and start/stop.' },
  { tag: 'ind-recipe-management-panel', category: 'shell', tier: 'organism', description: 'Recipe management panel to select, edit, load and save parameter sets.' },
  { tag: 'ind-device-diagnostics-panel', category: 'shell', tier: 'organism', description: 'Device diagnostics panel with identity, metrics and connection state.' },
  { tag: 'ind-firmware-update-panel', category: 'shell', tier: 'organism', description: 'Firmware update panel with current/target versions, progress and install flow.' },
  { tag: 'ind-event-journal', category: 'shell', tier: 'organism', description: 'Filterable event journal composed from event rows.' },
  { tag: 'ind-workstation-monitor', category: 'shell', tier: 'organism', description: 'Workstation monitor with operator, job, produced/rejected counts and state.' },
  { tag: 'ind-virtual-keyboard', category: 'shell', tier: 'organism', description: 'On-screen keyboard for touch panels, with show/hide events and locale.' },
];

/** Total component count, derived — never hard-coded in copy. */
export const COMPONENT_COUNT = COMPONENTS.length;

